workflows:
  android_build:
    name: Android Build & Test
    max_build_duration: 60 # minutes
    environment:
      # Using the Codemagic default Android environment
      android:
        version: 30 # Use the Android SDK version you need
        gradle: latest # Or specify a specific version of Gradle if necessary
    scripts:
      # Clean the project
      - echo "Cleaning the project..."
      - ./gradlew clean
      
      # Run unit tests (if you have any tests)
      - echo "Running unit tests..."
      - ./gradlew test
      
      # Build the release version of the app
      - echo "Building the release APK..."
      - ./gradlew assembleRelease

    artifacts:
      # Collect the APK and/or AAB files from the ou
